global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-prometheus'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'bsn-api:8083' ]

rule_files:
  - 'alert-rules.yml'

alerting:
  alertmanagers:
    - scheme: http
    - static_configs:
        - targets: [ 'alertmanager:9093' ]