route:
  receiver: tutorial-alert-manager
  repeat_interval: 1m
receivers:
  - name: 'tutorial-alert-manager'
  #  telegram_configs:
     # - bot_token: tutorial_token
      #  api_url: https://api.telegram.org
       # chat_id: -12345678
        #parse_mode: ''
    email_configs:
      - to: 'a.toujeni21369@pi.tn'
        from: 'ahmedtoujeni99@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'ahmedtoujeni99@gmail.com'
        auth_password: 'cjrb mwfq bhhl jiln'